### PR TITLE
use webdricer manager instead of manually managing the drivers.xml file

### PR DESCRIPTION
**Pull request by haiwan**
I did some experiments on a training project with the web driver manager (https://github.com/bonigarcia/webdrivermanager), it works quite nicely.

With the maven plugin, we no longer need to manage the drivers.xml file nor the driver-binary-downloader-maven-plugin.

Made this PR, so that you review it and see if it worths using it.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/250)

### CODE REVIEW

**Comment by haiwan** [comment]
@ZheSun88 How this plugin works is that the plugin author manages an online version of the drivers (https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/versions.properties), so I think Chrome 79, 80 or future versions should work out of the box. 

But a very good point, it's good to just use the latest version, pushed a new commit, thanks

**Comment by haiwan** [comment]
@ujoni problem number 2 indeed sounds serious. If you have time, maybe you can debug WebDriverManager::detectDriverVersionFromBrowser() to see why it insists using an older driver?

**Comment by ZheSun88** [comment]
It looks the problem NO.2 is not a problem any more. :-)

**Comment by shadikhani** [comment]
@haiwan we need this PR to be merged. Could you please resolve the conflicts?

**Comment by haijian-vaadin** [comment]
Hi @shadikhani, I will resolve the conflicts, Artur also gave some suggestions, I will do those as well. Will let you know once it's done.

**Comment by shadikhani** [comment]
@haiwan Thank you :)

**Comment by haijian-vaadin** [comment]
Instead of resolving the conflicts, I made a new PR https://github.com/vaadin/skeleton-starter-flow/pull/289, so closing this one

**Pull request closed without merging**
