### PR TITLE
Set logging dependency

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/64)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64#-:-L3RvSC9D23NhE9sF9JE:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
*[pom.xml, line 87 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64#-L3RvZySA2bDjp6CKVUP:-L3RvZySA2bDjp6CKVUQ:bfz0org) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/2b282e3af9d5550421df7dd35115cb335132c26d/pom.xml#L87)):*
> ```XML
>             <groupId>org.slf4j</groupId>
>             <artifactId>slf4j-simple</artifactId>
>             <version>1.7.25</version>
> ```

There's a property `slf4j.version` defined in the file, we can either remove it or use it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 87 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64#-L3RvZySA2bDjp6CKVUP:-L3Rx8RZCZ5gJJ1w52Ms:b-896fix) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/2b282e3af9d5550421df7dd35115cb335132c26d/pom.xml#L87)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

There's a property `slf4j.version` defined in the file, we can either remove it or use it here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 83 at r2](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64#-L3RxGjinM6aO9CQaFWA:-L3RxGjinM6aO9CQaFWB:b-jkxo24) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/7588765f3148a3614f8ffa5af667f6fcf604c861/pom.xml#L83)):*
> 

I've added a comment to another PR (another repository).
The same applies here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 83 at r2](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64#-L3RxGjinM6aO9CQaFWA:-L3RzMI8_SuTwnXUlAmF:b-896fix) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/7588765f3148a3614f8ffa5af667f6fcf604c861/pom.xml#L83)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> 

I've added a comment to another PR (another repository).
The same applies here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/64)*

**Pull request merged**
