### PR TITLE
Add pluginRepository definition

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/363)

### CODE REVIEW

**Comment by ZheSun88** [comment]
This is needed, otherwise maven will download the plugins from central via using `http://` instead of `https://`. 
related failure https://bender.vaadin.com/viewLog.html?buildId=176027&buildTypeId=VaadinPlatform_UpdateMavenStarters&tab=buildLog

**Comment by anasmi** [comment]
@ZheSun88 should it be added to all starters?

**Comment by ZheSun88** [comment]
so far, i haven't found the same issue with other starters. we can leave it for now..

**Comment by samie** [comment]
@ZheSun88 Good comment, since this sounds pretty weird... Maybe these kind of comments should be in the pom.xml code already to explain it to users also?

**Comment by ZheSun88** [comment]
@samie Added. #365

**Pull request merged**
