### PR TITLE
Add lumo theme to starter

### PR DESCRIPTION
**Pull request by caalador**
Note this PR requires a new Vaadin10 release to compile.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/62)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pom.xml, line 83 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62#-L31qClWvfRcPNiGgG7h:-L31qClXXP-kyQeXL88S:bri6i7s) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/31ea4d6f709a38164cc9c008a3fb22961010fa17/pom.xml#L83)):*
> <dependency>
>             <groupId>org.webjars.bower</groupId>
>             <artifactId>vaadin-valo-theme</artifactId>
>         </dependency>
>  
 Should we remove this one after we have `vaadin-lumo-theme`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62)*

**Comment by caalador** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 83 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62#-L31qClWvfRcPNiGgG7h:-L32-aYqguZyxQ6PIXGT:b-896fix) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/31ea4d6f709a38164cc9c008a3fb22961010fa17/pom.xml#L83)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> <dependency>
>             <groupId>org.webjars.bower</groupId>
>             <artifactId>vaadin-valo-theme</artifactId>
>         </dependency>
>  
 Should we remove this one after we have `vaadin-lumo-theme`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/62)*

**Pull request merged**
