### PR TITLE
Removed the @Theme declaration

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/80)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-:-L9FemFy59Jn_eS3nnKw:bnfp4nl)*

**Comment by caalador** [comment]
Will need to be updated to 10.0.0.beta7 to have the correct functionalities.
CLA not signed.

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 127 at r2](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-L9iGk5j7ffV5XWQFsMc:-L9iGk5j7ffV5XWQFsMd:b41po4a) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/58bcc23d0cbbaee92f19232946ac412111245f1a/pom.xml#L127)):*
> ```XML
>                         <groupId>com.vaadin</groupId>
>                         <artifactId>flow-maven-plugin</artifactId>
>                         <version>1.0.0.beta5</version>
> ```

I can see beta6 in the repo:
https://maven.vaadin.com/vaadin-prereleases/com/vaadin/flow-maven-plugin/

Should it be used?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-:-L9iG_Oq9g7w_fM4ZXSt:bnfp4nl)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 127 at r2](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-L9iGk5j7ffV5XWQFsMc:-L9iHT-U3IVlltz5-voh:b-snk4fa) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/58bcc23d0cbbaee92f19232946ac412111245f1a/pom.xml#L127)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I can see beta6 in the repo:
https://maven.vaadin.com/vaadin-prereleases/com/vaadin/flow-maven-plugin/

Should it be used?
</blockquote></details>

beta7 should probably be used as there was errors all around with beta5 and beta6.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 127 at r2](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-L9iGk5j7ffV5XWQFsMc:-L9iH_OF183CZJSGVHc6:bq3xwcp) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/58bcc23d0cbbaee92f19232946ac412111245f1a/pom.xml#L127)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

beta7 should probably be used as there was errors all around with beta5 and beta6.
</blockquote></details>

This is just the version of the plugin. There wasn't any changes to the plugin itself in the last releases after beta5.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 127 at r2](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-L9iGk5j7ffV5XWQFsMc:-L9iKxia--B4hx928tru:b-5j13xd) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/58bcc23d0cbbaee92f19232946ac412111245f1a/pom.xml#L127)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This is just the version of the plugin. There wasn't any changes to the plugin itself in the last releases after beta5.
</blockquote></details>

I already merged one of the PRs since I didn't notice @caalador's comment.
But beta7 doesn't even exist

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 127 at r2](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-L9iGk5j7ffV5XWQFsMc:-L9iMTwwENiKD771vAnZ:bm7m6qa) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/58bcc23d0cbbaee92f19232946ac412111245f1a/pom.xml#L127)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I already merged one of the PRs since I didn't notice @caalador's comment.
But beta7 doesn't even exist
</blockquote></details>

I think he is confusing it with the platform version.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pom.xml, line 127 at r2](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80#-L9iGk5j7ffV5XWQFsMc:-L9iahbG5C3_jS0yk8DM:b-oh5prr) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/58bcc23d0cbbaee92f19232946ac412111245f1a/pom.xml#L127)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I think he is confusing it with the platform version.
</blockquote></details>

I'll just merge this and update to beta6 in the BodySize PR

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/skeleton-starter-flow/80)*

**Pull request merged**
