### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by mstahv**
Removed obsoleted configurations and updated jetty

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/94)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/94#-LE8q4WBBOdcrBlfkD61:-LE8q4WBBOdcrBlfkD62:bl2mamt) (no related file):*
So does production mode works with jetty with those changes ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/94)*

**Comment by ZheSun88** [comment]
Besides Denis' comment, sign the CLA, please. @mstahv

**Comment by mstahv** [comment]
Yes, transpilation output is by default the target/finalname/ so the output ends up in war file.

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/94#-LE8q4WBBOdcrBlfkD61:-LE8xAOI2_g-GPo5uznD:b26u8ps) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

So does production mode works with jetty with those changes ?
</blockquote></details>

Hi Denis, i guess Matti replied this comment without using the reviewable. check the comment above. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/94)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/94#-:-LE8xcLS7ufKse1eaTcy:bnfp4nl)*

**Pull request merged**
