### PR TITLE
Add missing Valo theme, use publicly available plugin version.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/skeleton-starter-flow/52)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 78 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/52#-L-1Rr0_WaOdpdNiWfA-:-L-1Rr0_WaOdpdNiWfA0:b-3f0aaa) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/4f0bccb97b5945054490e7db7499021aad0e7397/pom.xml#L78)):*
> ```XML
>         </dependency>
> 
>         <dependency>
> ```

I am not sure why this is needed as a dependency. Could add a comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/52)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/52)*

**Comment by SomeoneToIgnore** [comment]
*[pom.xml, line 78 at r1](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/52#-L-1Rr0_WaOdpdNiWfA-:-L-1SQh3sJjGhdrxjZkW:b-896fix) ([raw file](https://github.com/vaadin/skeleton-starter-flow/blob/4f0bccb97b5945054490e7db7499021aad0e7397/pom.xml#L78)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

I am not sure why this is needed as a dependency. Could add a comment?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/52)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/skeleton-starter-flow/52)*

**Pull request merged**
